name: foofledrive
version: 0.7.9Î²
main: ga.ganma.foofledrive.Foofledrive
api-version: 1.13
commands:
  fl:
    description: ender cloud main command.
  foofledrive:
    description: ender cloud main command.